/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/video-player`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quran` | `/quran`; params?: Router.UnknownInputParams; } | { pathname: `/surah`; params?: Router.UnknownInputParams; } | { pathname: `/surah/juz`; params?: Router.UnknownInputParams; } | { pathname: `/surah/page`; params?: Router.UnknownInputParams; } | { pathname: `/surah/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/video-player`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/quran` | `/quran`; params?: Router.UnknownOutputParams; } | { pathname: `/surah`; params?: Router.UnknownOutputParams; } | { pathname: `/surah/juz`; params?: Router.UnknownOutputParams; } | { pathname: `/surah/page`; params?: Router.UnknownOutputParams; } | { pathname: `/surah/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/video-player${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/quran${`?${string}` | `#${string}` | ''}` | `/quran${`?${string}` | `#${string}` | ''}` | `/surah${`?${string}` | `#${string}` | ''}` | `/surah/juz${`?${string}` | `#${string}` | ''}` | `/surah/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/video-player`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quran` | `/quran`; params?: Router.UnknownInputParams; } | { pathname: `/surah`; params?: Router.UnknownInputParams; } | { pathname: `/surah/juz`; params?: Router.UnknownInputParams; } | { pathname: `/surah/page`; params?: Router.UnknownInputParams; } | `/surah/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/surah/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
